### ISSUE TITLE
notes on transitions() iterator

### ISSUE THREAD

**Issue by belm0** [groove-x/trio-util#8]
Notes on a `transitions(predicate)` iterator, corresponding to `wait_transition()`.

Intending to take small steps with this.  The initial semantics would be rudimentary, building on the existing core and equating to this loop:

```python
async def transitions(predicate):
    while True:
        yield await self.wait_transition(predicate)
```

It implies that transitions while the user is blocked in the iteration body will be missed.  (Similar to semantics of `UnqueuedRepeatedEvent`.)

If there is no blocking in the iteration body, and the `AsyncValue` mutation is constrained to once per round of the Trio scheduler, ~then all transitions could be captured~.  This suggests an optional queueing implementation, still based on the existing core, using memory channels.  (If the queue size was limited, the sender would not block.  Either it's an exception for the iteration, or the receiver misses transitions.) Since yield from nursery within a generator is not allowed, the API would have to hop through a context manager:

```python
async with x.transitions(lambda val: x > 0, max_buffer_size=inf) as transitions:
    async with _ in transitions:
        ...
```

**Comment by belm0** [comment]
> If there is no blocking in the iteration body, and the AsyncValue mutation is constrained to once per round of the Trio scheduler, then all transitions could be captured

I've learned that this is not true.  Since both the producer and consumer tasks could be scheduled in the same trio frame (presumably for the consumer to receive the last frame's value, and producer to send the next value), and since the scheduling order within the frame is not deterministic, it's possible that the producer task may run first and overwrite the previous frame's value before the consumer reads it.

So it may be time to explore implementing AsyncValue predicates with a memory channel, for example of size 1 and with non-blocking send that either throws or drops on overflow.

**Comment by mozesa** [comment]
Hello **John**,

I am always amazed how useful this library is.

`async_value.transitions()` would be really useful but it seems to me that version being on pypi doesn't contain this.

Is there some reasons behind scenes not to released?

Thanks for your help in advance.

**Comment by belm0** [comment]
@mozesa thank you-- I've release trio-util 0.4.0, which includes `transitions()`

**Comment by belm0** [comment]
## eventual consistency use case

In hindsight, `transitions()` doesn't cover a common use case I'll call "eventual consistency", where we want to ensure that the latest value always propagates.  Users naively try to use `transitions()` in this situation and end up with unexpected or buggy behavior.

  1. The user-supplied `transitions()` predicate most often isn't concerned with the old value (e.g. the default predicate of any transition).  Even when the predicate is a function of the current value only, transitions are dropped when the caller is blocked in the loop body, so a matching value may persist yet never appear on the iterator.
  2. To be consistent with the current value, often it's desirable to run the loop body once immediately.  But this notion conflicts with the predicate, which is a function of old and new value.  As a consequence, users often must fret about initialization timing so that their `transitions()` loop catches the first intended value-- a source of bugs and race conditions.

For (1) I prototyped an option where up to one transition is captured while the body is blocked.   But I'm not confident this is the way to go since it doesn't address (2).

Understanding the limitations of `transitions()`, to achieve eventually consistency we often we fall back to the following idiom of blocking for a value change at the end of a `while` loop:

```python3
# process_value() is run on values (including current value), with eventual consistency
last_value = async_val.value
while True:
    await process_value(last_value)  # may block for a while
    last_value = await async_val.wait_value(lambda val: val != last_value)   
```

So this suggests a competitor to `transitions()` more suitable for eventual consistency.  Like `wait_value()`, it takes a predicate of the current value only.   It might be called `values()` or `eventual_values()`.  Equivalent to the previous example:

```python3
# process_value() is run on values (including current value), with eventual consistency
async for value in async_val.eventual_values():   # all values by default
    await process_value(value)

# same, with a predicate filter
async for value in async_val.eventual_values(lambda x: x > 10):
    await process_value(value)
```

If the implementation uses the naive "wait for value different than last seen" pattern it will suffer from an A-B-A issue, but that doesn't affect eventual consistency.  The A-B-A problem can be avoided in various ways, such as maintaining a value generation.

**Comment by belm0** [comment]
`eventual_values()` is proving effective in our trial so far.  I'll add the implementation to this repo soon.

Comparison of `eventual_values()` and `transitions()`:
```
eventual_values()                      transitions()
=================                      =============
• high level & safe                    • low level & requires care
• evaluated on each value change,      • evaluated on each value change
    and when starting loop                 if caller not blocked in the body
• eventually iterates lastest value    • latest value missed if caller is blocked
• can miss rapid value changes         • can miss rapid value changes
• condition uses new value only        • condition uses new and/or old value
• mainly used for sync'ing state       • mainly used for triggering work
• not subject to user races            • races possible on init and each iteration
                                           (especially if value changes infrequently)
```

**Comment by belm0** [comment]
trio-util 0.5.0 includes the `eventual_values()` iterator

`eventual_values()` covers some important use cases while being simpler and less prone to mistakes, so there is less motivation to add features to `transitions()`
